BUTTON_OPEN_IMG = 'BUTTON_OPEN_IMG'
BUTTON_LOAD_CONFIG = 'BUTTON_LOAD_CONFIG'
BUTTON_SAVE_IMG = 'BUTTON_SAVE_IMG'
BUTTON_SAVE_CONFIG = 'BUTTON_SAVE_CONFIG'
BUTTON_CAPTURE_IMG = 'BUTTON_CAPTURE_IMG'
BUTTON_START_DETECTION = 'BUTTON_START_DETECTION'
BUTTON_LOAD_VIDEO = 'BUTTON_LOAD_VIDEO'

SOURCE_IMG_PATH = 'SOURCE_IMG_PATH'
SOURCE_VIDEO_PATH = 'SOURCE_VIDEO_PATH'
SOURCE_IMG_CV2 = 'SOURCE_IMG_CV2'
MASK_IMG_CV2 = 'MASK_IMG_CV2'
OUTPUT_IMG_CV2 = 'OUTPUT_IMG_CV2'
OUTPUT_IMG_QT = 'OUTPUT_IMG_QT'

IMAGE_DICT_KEYS = [SOURCE_IMG_PATH, SOURCE_IMG_CV2, MASK_IMG_CV2, OUTPUT_IMG_CV2, OUTPUT_IMG_QT]

SLIDER_LABELS = ["R/H Lower", "G/S Lower", "B/V Lower", "R/H Upper", "G/S Upper", "B/V Upper"]

CSV_CONFIG_KEYS = ['key' , 'value']

# PLACEHOLDER IMAGE PATH:
PLACEHOLDER_IMG_PATH = "GUI/images/placeholder.jpg"

# YOLO CONFIGS
YOLO_WEIGHT_PATH = "YOLO_WEIGHT_PATH"
YOLO_CONFIG_PATH = "YOLO_CONFIG_PATH"

# Various labels:
VIDEO_PATH_LABEL = "video_path"
IMAGE_PATH_LABEL = "image_path"
WEIGHT_PATH_LABEL = "weight_path"
CFG_PATH_LABEL = "cfg_path"

# Tracker:
CHOSEN_TRACKER = "CHOSEN_TRACKER"