BUTTON_OPEN_IMG = 'BUTTON_OPEN_IMG'
BUTTON_LOAD_CONFIG = 'BUTTON_LOAD_CONFIG'
BUTTON_SAVE_IMG = 'BUTTON_SAVE_IMG'
BUTTON_SAVE_CONFIG = 'BUTTON_SAVE_CONFIG'
BUTTON_CAPTURE_IMG = 'BUTTON_CAPTURE_IMG'
BUTTON_START_DETECTION = 'BUTTON_START_DETECTION'

SOURCE_IMG_PATH = 'SOURCE_IMG_PATH'
SOURCE_IMG_CV2 = 'SOURCE_IMG_CV2'
MASK_IMG_CV2 = 'MASK_IMG_CV2'
OUTPUT_IMG_CV2 = 'OUTPUT_IMG_CV2'
OUTPUT_IMG_QT = 'OUTPUT_IMG_QT'

IMAGE_DICT_KEYS = [SOURCE_IMG_PATH, SOURCE_IMG_CV2, MASK_IMG_CV2, OUTPUT_IMG_CV2, OUTPUT_IMG_QT]

SLIDER_LABELS = ["R/H Lower", "G/S Lower", "B/V Lower", "R/H Upper", "G/S Upper", "B/V Upper"]

CSV_CONFIG_KEYS = ['key' , 'value']