CSRT = "CSRT"
KCF = "KCF"
BOOSTING = "BOOSTING"
MIL = "MIL"
TLD = "TLD"
MEDIANFLOW = "MEDIANFLOW"
MOSSE = "MOSSE"
NO_TRACKER = "NO_TRACKER"

# message strings:
TRACKER_DEFAULT = "KCF"
TRACKER_PREFIX = "Selected Tracker: "